dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('',views.dashboard, name="dashboard"),
    path('properties/addproperty',views.addproperty, name="addproperty"),
    path('properties/addproject',views.addproject, name="addproject"),
    path('properties/allproperties',views.allproperties, name="allproperties"),
    path('properties/allproject',views.allprojects, name="allprojects"),
    path('supervisor/',views.supervisordashboard, name="sdashboard"),
    path('supervisor/properties',views.property_verification, name="propertyverification"),
    path('supervisor/projects',views.project_verification, name="projectverification"),
    # path('builder/projects/delete',views.project_delete, name="projectdelete"),
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'realestate'

urlpatterns = [
    path('',views.index, name="index"),
    path('otp-success/',views.otpsuccess, name="otpsuccess"),
    path('auth/register/',views.register, name="register"),
    path('auth/login/',views.signin, name="login"),
    path('auth/register/otp/<phoneno>/',views.otp, name="otp"),
    path('auth/register/resendotp/',views.resendotp, name="resendotp"),
    path('auth/logout/',views.user_logout, name = 'logout'),
    
    path('marketplace/',views.marketplace, name="marketplace"),
    path('property/<slug>',views.property, name="property"),
    path('project/<slug>',views.project, name="project"),
    
    path('contact/',views.contact, name="contact"),
    path('about/',views.about, name="about"),
    path('profile/',views.profile, name="profile"),
    path('terms&conditions/',views.tc, name="tc"),
    path('privacypolicy/',views.privacypolicy, name="privacypolicy"),
]

realEstateManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('marketplace.urls')),
    path('dashboard/',include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

marketplace/models.py
from django.db import models
from django.contrib.auth.models import User

# from dashboard.models import Property

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneno = models.CharField(max_length=10)
    otp = models.CharField(max_length=4, null=True, blank=True)
    is_verified = models.BooleanField(default=False)
    forgot_password_token = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    choices = (
        ('Buyer','Buyer'),
        ('Seller','Seller'),
        ('Builder','Builder'),
    )
    usertype = models.CharField(max_length=30, choices=choices, default='Buyer')

    class Meta:
        permissions = {
            ("buyer","buyer"),
            ("seller","seller"),
            ("builder","builder"),
            ("supervisor","supervisor")
        }    

    def __str__ (self):
        return self.user.username

# from django.db import models
 
# class Post(models.Model):
#     title = models.CharField(max_length=250)
#     description = models.TextField()
#     image = models.FileField(blank=True)
 
#     def __str__(self):
#         return self.title
 
# class PostImage(models.Model):
#     post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
#     images = models.FileField(upload_to = 'images/')
 
#     def __str__(self):
#         return self.post.title


# price, rent/sell, bhk, area, address, city, state

marketplace/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
import requests
from dashboard.models import *
from marketplace.otp import *
from .models import *
from django.contrib.auth import authenticate, login, logout
import random
from django.contrib.auth.models import Group
from django.core.mail import send_mail


# Create your views here.
def index(request):
    properties = Property_image.objects.all()[0:20]
    project = Project.objects.filter(is_verified=True)[0:2]
    context = {"properties": properties, "project":project}
    return render(request, 'index.html', context)


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        emailid = request.POST.get('emailid')
        password = request.POST.get('password')
        phoneno = request.POST.get('phoneno')
        usertype = request.POST.get('usertype')
        # list1 = [username,emailid,password,phoneno,usertype]
        # print(list1)

        try:
            if len(password) < 6:
                messages.error(request, 'Password is too short.')

            if len(phoneno) < 10:
                messages.error(request, 'Contact no is wrong.')

            else:
                if User.objects.filter(username=username).first():
                    messages.error(request, 'Username is taken.')
                    return redirect('realestate:auth/register/')
                if User.objects.filter(email=emailid).first():
                    messages.error(request, 'Email id is taken.')
                    return redirect('realestate:auth/register/')
                if Profile.objects.filter(phoneno=phoneno).first():
                    messages.error(request, 'Contact no is taken.')
                    return redirect('realestate:auth/register/')

                user_obj = User(username=username, email=emailid)
                user_obj.set_password(password)
                user_obj.save()
                otp = str(random.randrange(1000, 9999))
                profile_obj = Profile.objects.create(
                    user=user_obj, phoneno=phoneno, usertype=usertype, otp=otp)
                profile_obj.save()
                if profile_obj.is_verified:
                    messages.error(request, 'Contact no already verified.')
                    return redirect('realestate:auth/register/')
                else:
                    send_otp_code(phoneno, otp)
                    request.session['phoneno'] = phoneno
                    group = Group.objects.get(name=usertype)
                    user_obj.groups.add(group)
                return redirect(reverse('realestate:otp', kwargs={'phoneno': phoneno}))
        except Exception as e:
            print(e)
    return render(request, 'register.html')


def otp(request, phoneno):
    if request.method == 'POST':
        otp1 = request.POST.get('otp1')
        otp2 = request.POST.get('otp2')
        otp3 = request.POST.get('otp3')
        otp4 = request.POST.get('otp4')
        otp = str(otp1+otp2+otp3+otp4)
        print(otp)
        data = Profile.objects.get(phoneno=phoneno)
        if otp == data.otp:
            data.is_verified = True
            data.save()
            messages.success(request, 'Contact no succssfully verified.')
            return redirect('/otp-success')
        else:
            messages.error(request, 'Please enter valid OTP.')

    context = {'phoneno': phoneno}
    return render(request, 'otp.html', context)


def resendotp(request):
    phoneno = request.session['phoneno']
    print(phoneno)
    data = Profile.objects.get(phoneno=phoneno)
    otp = str(random.randrange(1000, 9999))
    data.otp = otp
    data.save()
    # print(otp)
    send_otp_code(phoneno, otp)
    return redirect(reverse('realestate:otp', kwargs={'phoneno': phoneno}))


def otpsuccess(request):
    return render(request, 'otpsuccess.html')


def signin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_obj = User.objects.filter(username=username).first()

        if user_obj is None:
            messages.error(request, 'User not found')
            return redirect('/auth/login')

        profile_obj = Profile.objects.filter(user=user_obj).first()

        if not profile_obj.is_verified:
            messages.error(
                request, 'User is not verified pls verify your contact no')
            return redirect('/auth/login')

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Login successfully')
            return redirect('/')
        else:
            messages.error(request, 'Wrong password or email')
            return redirect('/auth/login')

    return render(request, 'login.html')


def user_logout(request):
    logout(request)
    messages.success(request, 'logged out')
    return redirect('/')


def contact(request):
    if request.method == 'POST':
        fn = request.POST.get('firstname')
        ln = request.POST.get('lastname')
        subject = request.POST.get('subject')
        email = request.POST.get('email')
        msg = request.POST.get('message')

        try:
            message = fn + ln + email + msg
            send_mail(subject, message, email, [settings.EMAIL_HOST_USER])
            messages.success(request, 'successfully send')
            return redirect('/')
        except Exception as e:
            print(e)
    return render(request, 'contact.html')


def about(request):
    return render(request, 'about.html')


def tc(request):
    return render(request, 't&c.html')


def privacypolicy(request):
    return render(request, 'privacypolicy.html')


def marketplace(request):
    states_url = "https://api.countrystatecity.in/v1/countries/IN/states"
    cities_url = "https://api.countrystatecity.in/v1/countries/IN/cities"
    headers = {
        'X-CSCAPI-KEY': 'blhwU1g0VUZ4Wm1lck8zeTg5WjZIN1dvZ0JHR09NUmJrcjlTYzVRZw=='
    }
    states = requests.request("GET", states_url, headers=headers).json()
    cities = requests.request("GET", cities_url, headers=headers).json()
    property_type = Property_type.objects.all()

    # searchbar
    propertytype = ""
    purpose = ""
    state = ""
    city = ""
    properties = None
    if request.method == 'POST':
        propertytype = request.POST.get('propertytype')
        purpose = request.POST.get('purpose')
        state = request.POST.get('state')
        city = request.POST.get('city')

    try:
        property_obj = Property.objects.get(
        property_type=propertytype, property_purpose=purpose, property_state=state, property_city=city)
        properties = Property_image.objects.filter(property=property_obj)
    except Property.DoesNotExist:
        properties = Property_image.objects.all()
    
    context = {"properties": properties, "property_type": property_type, "cities": cities, "states": states}
    return render(request, 'marketplace.html', context)


def property(request, slug):
    property1 = Property_image.objects.filter(slug=slug)
    # profile = Profile.objects.filter()
    context = {"propertydetails": property1}
    return render(request, 'singleproperty.html', context)

def project(request, slug):
    project = Project.objects.filter(slug=slug)
    print(project)
    # profile = Profile.objects.filter()
    context = {"projects": project}
    return render(request, 'singleproject.html', context)


def profile(request):
    profile = Profile.objects.filter(user = request.user)
    context = {"profile": profile}
    if request.method == 'POST':
        cp = request.POST.get('currentpassword')
        np = request.POST.get('newpassword')
        print(cp)
        print(np)

        user = User.objects.get(username = request.user)

        user.check_password(cp)
        if user.check_password(cp):
            user.set_password(np)
            user.save()
            messages.success(request, 'Your password successfully changed.')
        else:
            return redirect('/profile')
      
          
    return render(request, 'profile.html', context)

marketplace/templates/about.html
{% extends "main.html" %}

{% block title %}
About | Area360
{% endblock title %}

{% block body %}

<!--First row-->
<div class="container my-5">
    <h2 class="h2-responsive mb-5 text-center">About us</h2>
    <div class="row">
        <div class="col-md-7">
            <!--Featured image -->
            <div>
                <img src="https://mdbootstrap.com/images/proffesions/slides/socialmedia/img%20(2).jpg"
                    class="img-fluid " alt="">
            </div>
            <br>
        </div>

        <!--Main information-->
        <div class="col-md-5">
            <p>Welcome to our real estate company! We are a team of dedicated professionals with a passion for helping
                our clients find the perfect property. Whether you are looking to buy, sell, or rent, we are here to
                assist you every step of the way.<br><br>

                Our company was founded on the belief that the real estate process should be transparent,
                straightforward, and stress-free. We strive to provide excellent customer service and go above and
                beyond to ensure that our clients are satisfied with their experience.<br><br>
            </p>
        </div>
    </div>
    <p>We have a diverse team of agents with a wealth of knowledge and experience in the industry. Each of our
        agents has their own specialty, whether it be residential, commercial, or investment properties. We also
        have a team of professionals who handle all aspects of the transaction process, including financing,
        closing, and property management.<br><br>

        Our extensive network of resources allows us to offer a wide range of properties to our clients. From
        luxurious homes to affordable apartments, we have something for everyone. We are also constantly
        updating our database with new listings to ensure that our clients have access to the latest properties
        on the market.<br><br>

        In addition to our team of agents, we also have a dedicated marketing department that works to showcase
        our listings to potential buyers and renters. We utilize a variety of marketing strategies, including
        social media, email campaigns, and targeted advertising to reach the right audience.<br><br>

        One of the things that sets us apart from other real estate companies is our commitment to community
        involvement. We believe that it is important to give back to the communities in which we work and live.
        We are actively involved in a number of local charities and organizations, and we regularly host events
        to raise money and awareness for important causes.<br><br>

        We understand that purchasing or selling a property can be a daunting task, which is why we are here to
        guide you through every step of the process. Our team is always available to answer any questions or
        concerns you may have. <br><br>

        Thank you for considering our company for your real estate needs. We look forward to working with you
        and helping you achieve your real estate goals.</p>
</div>
<!--/.First row-->

{% endblock body %}

marketplace/templates/contact.html
{% extends "main.html" %}

{% block title %}
Contact | Area360
{% endblock title %}
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <script>
        alert('{{ message }}');
    </script>
    {% endfor %}
</div>
{% endif %}

{% block body %}
<div class="container-sm my-5 w-50 btn-outline-light p-4">
    <h2 class="h2-responsive text-center mb-5">Contact us</h2>
    <form action="#" method="post">
        {% csrf_token %}
        <div class="row mb-4">
            <div class="col">
                <div class="input-group">
                    <input type="text" class="form-control" name="firstname" placeholder="First name" aria-label="First name" required/>
                </div>
            </div>
            <div class="col">
                <div class="input-group">
                    <input type="text" class="form-control" name="lastname" placeholder="Last name" aria-label="Last name" required/>
                </div>
            </div>
        </div>

        <!-- Email input -->
        <div class="input-group mb-4">
            <input type="email" class="form-control" name="email" placeholder="Email id" aria-label="Email id" required />
        </div>
        
        <div class="input-group mb-4">
            <input type="text" class="form-control" name="subject" placeholder="subject" aria-label="subject" required />
        </div>
        <!-- Password input -->
        <div class="mb-4">
            <textarea class="form-control" rows="5" name="message" placeholder="Message" aria-label="Message" required></textarea>
        </div>

        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
    </form>
</div>
{% endblock body %}

marketplace/templates/login.html
{% extends "main.html" %}

{% block title %}
Login | Area360
{% endblock title %}

{% block body %}
{% if messages %}
<div class="messages">
  {% for message in messages %}
  <script>
    alert('{{ message }}');
  </script>
  {% endfor %}
</div>
{% endif %}
<div class="container-sm my-5 w-25 btn-outline-light p-4">
  <h2 class="h2-responsive text-center mb-5">Welcome back</h2>
  <form action="#" method="post" class="text-center">
    {% csrf_token %}

    <!-- Email input -->
    <div class="input-group mb-4">
      <input type="username" class="form-control" name="username" placeholder="Username" aria-label="Username"
        required />
    </div>
    <!-- Password input -->
    <div class="input-group mb-4">
      <input type="password" class="form-control" name="password" placeholder="Password" aria-label="Password"
        required />
    </div>

    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Login</button>

    <!-- Register buttons -->
    <!-- <div class="text-center">
    <p>or sign up with:</p>
    <button type="button" class="btn btn-secondary btn-floating mx-1">
      <i class="fab fa-facebook-f"></i>
    </button>

    <button type="button" class="btn btn-secondary btn-floating mx-1">
      <i class="fab fa-google"></i>
    </button>

    <button type="button" class="btn btn-secondary btn-floating mx-1">
      <i class="fab fa-twitter"></i>
    </button>

    <button type="button" class="btn btn-secondary btn-floating mx-1">
      <i class="fab fa-github"></i>
    </button>
  </div> -->
  </form>
</div>
{% endblock body %}

marketplace/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>

  <!-- MDB icon -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
  <!-- Google Fonts Roboto -->
  <!-- <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" /> -->

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Nunito:wght@300;400;500;600;700;800&display=swap"
    rel="stylesheet">
  <!-- MDB -->
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
  <!-- <link rel="stylesheet" href="{% static 'css/mdb.dark.min.css' %}" /> -->
  <link rel="stylesheet" href="{% static 'css/mdb.rtl.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />

</head>

<body>


  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Container wrapper -->
    <div class="container-fluid ">
      <!-- Toggle button -->
      <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Navbar brand -->

      <span class="navbar-brand mb-0 h1 fw-bolder text-primary">Area360</span>
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item me-2">
            <a class="nav-link" href="{% url 'realestate:index' %}">Home</a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link" href="{% url 'realestate:marketplace' %}">Marketplace</a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link" href="{% url 'realestate:about' %}">About</a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link" href="{% url 'realestate:contact' %}">Contact</a>
          </li>
        </ul>
        <!-- Left links -->
        {% if not user.is_authenticated %}
        <div class="d-flex align-items-center">
          <a type="button" class="btn btn-secondary px-3 me-2" href="{% url 'realestate:login' %}">
            Login
          </a>
          <a type="button" class="btn btn-primary me-3" href="{% url 'realestate:register' %}">
            Signup
          </a>
        </div>
        {% endif %}
      </div>

      {% if user.is_authenticated %}
      <div class="dropdown me-3">
        <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar"
          role="button" data-mdb-toggle="dropdown" aria-expanded="false">
          <img src="{% static 'img/avatar.png' %}" class="rounded-circle" height="25"
            alt="Black and White Portrait of a Man" loading="lazy" />
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">
          <li>
            {% if user.is_staff %}
            <a class="dropdown-item" href="{% url 'sdashboard' %}">Dashboard</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'dashboard' %}">Dashboard</a>
            {% endif %}
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'realestate:profile' %}">Profile</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'realestate:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
    {% endif %}
    <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->



  {% block body %}
  {% endblock body %}


  <!-- Footer -->
  <footer class="text-center text-lg-start text-muted" style="background-color: rgba(0, 0, 0, 0.025);">
    <!-- Section: Links  -->
    <section class="pt-2">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4 text-primary">
              <i class="fas fa-gem me-3 text-primary"></i>Area360
            </h6>
            <p>
              Area360 is plateform to buy, sell and rent all types of properties.
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4 text-primary">
              properties
            </h6>
            <p>
              <a href="#!" class="text-reset">Apartment</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Flate</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Warehouse</a>
            </p>
            <p>
              <a href="#!" class="text-reset">House</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4 text-primary">
              Useful links
            </h6>
            <p>
              <a href="{% url 'realestate:index' %}" class="text-reset">Home</a>
            </p>
            <p>
              <a href="{% url 'realestate:about' %}" class="text-reset">About</a>
            </p>
            <p>
              <a href="{% url 'realestate:contact' %}" class="text-reset">Contact</a>
            </p>
            <p>
              <a href="{% url 'realestate:privacypolicy' %}" class="text-reset">Privacy Policy</a>
            </p>
            <p>
              <a href="{% url 'realestate:tc' %}" class="text-reset">Terms & conditions</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4 text-primary">Contact</h6>
            <p><i class="fas fa-home me-3 text-secondary"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3 text-secondary"></i>
              support@area360.com
            </p>
            <p><i class="fas fa-phone me-3 text-secondary"></i> + 91 9904557484</p>
            <p><i class="fas fa-print me-3 text-secondary"></i> + 91 6453245679</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a class="btn text-white btn-floating m-1" style="background-color: #3b5998;" href="#!" role="button"><i
              class="fab fa-facebook-f"></i></a>

          <!-- Twitter -->
          <a class="btn text-white btn-floating m-1" style="background-color: #55acee;" href="#!" role="button"><i
              class="fab fa-twitter"></i></a>

          <!-- Google -->
          <a class="btn text-white btn-floating m-1" style="background-color: #dd4b39;" href="#!" role="button"><i
              class="fab fa-google"></i></a>

          <!-- Instagram -->
          <a class="btn text-white btn-floating m-1" style="background-color: #ac2bac;" href="#!" role="button"><i
              class="fab fa-instagram"></i></a>

          <!-- Linkedin -->
          <a class="btn text-white btn-floating m-1" style="background-color: #0082ca;" href="#!" role="button"><i
              class="fab fa-linkedin-in"></i></a>

        </section>
        <!-- Section: Social media -->
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">Area360.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

  <!-- MDB -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

  <!-- sweetalert -->
  <!-- <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> -->

  <!-- Custom scripts -->
  <script type="text/javascript" sec="{% static 'js/script.js' %}"></script>


  <!-- chatbot -->
  <!--Start of Tawk.to Script-->
  <script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
      var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
      s1.async = true;
      s1.src = 'https://embed.tawk.to/641e9f2d4247f20fefe7e0f5/1gsbprjhb';
      s1.charset = 'UTF-8';
      s1.setAttribute('crossorigin', '*');
      s0.parentNode.insertBefore(s1, s0);
    })();
  </script>
  <!--End of Tawk.to Script-->
</body>

</html>

marketplace/templates/otp.html
{% extends "main.html" %} {% block title %} otp | Area360 {% endblock title %}
{% block body %}
<!-- <div class="container-sm my-5 w-50 btn-outline-light p-4">
    <h2 class="h2-responsive text-center mb-5">Register</h2>
    <form action="#" method="post">
        {% csrf_token %}
            <input class="otp" type="text" oninput='digitValidate(this)' onkeyup='tabChange(1)' maxlength=1 >
            <input class="otp" type="text" oninput='digitValidate(this)' onkeyup='tabChange(2)' maxlength=1 >
            <input class="otp" type="text" oninput='digitValidate(this)' onkeyup='tabChange(3)' maxlength=1 >
            <input class="otp" type="text" oninput='digitValidate(this)'onkeyup='tabChange(4)' maxlength=1 >
    </form>
</div> -->
<div class="container-sm my-5 w-25 btn-outline-light p-4">
  <h5 class="h5-responsive text-center mb-3">
    Please enter OTP to verify your account
  </h5>
  <p class="text-center mb-3">A code has been sent to {{phoneno}}</p>
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <p class="text-danger">{{message}}</p>
    {% endfor %}
  </div>
  {% endif %}
  <form action="" method="post" class="mt-5">
    <div class="row mb-4">
      <div class="col">
        <input class="form-control otp text-center" type="text" name="otp1" oninput="digitValidate(this)"
          onkeyup="tabChange(1)" maxlength="1" />
      </div>
      <div class="col">
        <input class="form-control otp text-center" type="text" name="otp2" oninput="digitValidate(this)"
          onkeyup="tabChange(2)" maxlength="1" />
      </div>
      <div class="col">
        <input class="form-control otp text-center" type="text" name="otp3" oninput="digitValidate(this)"
          onkeyup="tabChange(3)" maxlength="1" />
      </div>
      <div class="col">
        <input class="form-control otp text-center" type="text" name="otp4" oninput="digitValidate(this)"
          onkeyup="tabChange(4)" maxlength="1" />
      </div>
    </div>
    <div id="resendotp" class="mb-3">
      <a href="{% url 'realestate:resendotp' %}" class="color-primary">Resend OTP</a>
    </div>
    {% csrf_token %}
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Verify</button>
  </form>
</div>

<script>
  let digitValidate = function (ele) {
    console.log(ele.value);
    ele.value = ele.value.replace(/[^0-9]/g, "");
  };

  let tabChange = function (val) {
    let ele = document.querySelectorAll("input");
    if (ele[val - 1].value != "") {
      ele[val].focus();
    } else if (ele[val - 1].value == "") {
      ele[val - 2].focus();
    }
  };

  let rd = document.getElementById("resendotp")
  rd.style.display = "none";

  setTimeout(() => {
    rd.style.display = "block";
  }, 60000);

</script>
{% endblock body %}

marketplace/templates/otpsuccess.html
{% extends "main.html" %} 
{% block title %} 
Success | Area360 
{% endblock title %} 
{% block body %}
<div class="container-sm my-5 w-25 btn-outline-light p-4 text-center py-5">
  <h5 class="h5-responsive text-center mb-3">
    Your account is successfully verified.
  </h5>
  <a class="btn btn-primary mt-5" href="{% url 'realestate:index' %}">Go to Dashboard</a>
</div>
{% endblock body %}