dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('',views.dashboard, name="dashboard"),
    path('properties/addproperty',views.addproperty, name="addproperty"),
    path('properties/addproject',views.addproject, name="addproject"),
    path('properties/allproperties',views.allproperties, name="allproperties"),
    path('properties/allproject',views.allprojects, name="allprojects"),
    path('supervisor/',views.supervisordashboard, name="sdashboard"),
    path('supervisor/properties',views.property_verification, name="propertyverification"),
    path('supervisor/projects',views.project_verification, name="projectverification"),
    # path('builder/projects/delete',views.project_delete, name="projectdelete"),
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'realestate'

urlpatterns = [
    path('',views.index, name="index"),
    path('otp-success/',views.otpsuccess, name="otpsuccess"),
    path('auth/register/',views.register, name="register"),
    path('auth/login/',views.signin, name="login"),
    path('auth/register/otp/<phoneno>/',views.otp, name="otp"),
    path('auth/register/resendotp/',views.resendotp, name="resendotp"),
    path('auth/logout/',views.user_logout, name = 'logout'),
    
    path('marketplace/',views.marketplace, name="marketplace"),
    path('property/<slug>',views.property, name="property"),
    path('project/<slug>',views.project, name="project"),
    
    path('contact/',views.contact, name="contact"),
    path('about/',views.about, name="about"),
    path('profile/',views.profile, name="profile"),
    path('terms&conditions/',views.tc, name="tc"),
    path('privacypolicy/',views.privacypolicy, name="privacypolicy"),
]

realEstateManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('marketplace.urls')),
    path('dashboard/',include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

from marketplace.models import Profile

# from marketplace.models import Profile

# Create your models here.

class Property_type(models.Model):
    property_type = models.CharField(max_length=30)

    def __str__(self):
        return self.property_type


class Property(models.Model):
    type = (
        ('Rent', 'Rent'),
        ('Sell', 'Sell'),
    )
    posting_as_a = (
        ('Full House', 'Full House'),
        ('On sharing basis', 'On sharing basis'),
    )
    age_of_construction = (
        ('less than 5 years', 'less than 5 years'),
        ('5 to 10 years', '5 to 10 years'),
        ('10 to 20 years', '10 to 20 years'),
        ('More than 20', 'More than 20'),
    )
    furnished = (
        ('Full Furnished', 'Full Furnished'),
        ('No Furnished', 'No Furnished'),
    )
    user_seller = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    property_purpose = models.CharField(max_length=10, choices=type)
    property_type = models.CharField(max_length=50)
    property_posting = models.CharField(max_length=30, choices=posting_as_a, default="On sharing basis", null=True, blank=True)
    property_address = models.CharField(max_length=200)
    property_state = models.CharField(max_length=100)
    property_city = models.CharField(max_length=100)
    # property_floor_no = models.IntegerField(null=True, blank=True)
    # property_area = models.IntegerField(null=True, blank=True)
    property_age_of_construction = models.CharField(
        max_length=100, choices=age_of_construction, null=True, blank=True)
    # property_floors_allowed_for_construction = models.IntegerField(blank=True)
    # property_no_of_open_sides = models.IntegerField(null=True, blank=True)
    property_bountry_wall = models.CharField(
        max_length=20, null=True, blank=True)
    property_furnished_status = models.CharField(
        max_length=50, choices=furnished, null=True, blank=True, default="No Furnished")
    # property_monthly_rent = models.IntegerField(null=True, blank=True)
    # property_maintenance_charges = models.IntegerField(null=True, blank=True)
    # property_price = models.IntegerField(null=True, blank=True)
    # property_booking_price = models.IntegerField(null=True, blank=True)
    dynamic_fields = models.JSONField(default=None)
    is_verified = models.BooleanField(default=False)
    property_no = models.CharField(max_length=100, unique=True, null=True, blank=True)

    def __str__(self):
        return self.property_type


class Property_image(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    image1 = models.ImageField(upload_to="images/")
    image2 = models.ImageField(upload_to="images/", default="")
    image3 = models.ImageField(upload_to="images/", default="")
    image4 = models.ImageField(upload_to="images/", default="")
    image5 = models.ImageField(upload_to="images/", default="")
    slug = models.SlugField(unique=True)


class Project(models.Model):
    furnished = (
        ('Full Furnished', 'Full Furnished'),
        ('No Furnished', 'No Furnished'),
    )

    builder = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    projectname = models.CharField(max_length=100, blank=True, null=True)
    property_type = models.CharField(max_length=50)
    property_address = models.CharField(max_length=200)
    property_state = models.CharField(max_length=100)
    property_city = models.CharField(max_length=100)
    dynamic_fields = models.JSONField(default=None)
    property_furnished_status = models.CharField(max_length=50, choices=furnished, null=True, blank=True, default="No Furnished")
    is_verified = models.BooleanField(default=False)
    image1 = models.ImageField(upload_to="images/")
    image2 = models.ImageField(upload_to="images/", default="")
    image3 = models.ImageField(upload_to="images/", default="")
    image4 = models.ImageField(upload_to="images/", default="")
    image5 = models.ImageField(upload_to="images/", default="")
    booklet = models.FileField(upload_to="booklet/", default="")
    companyname = models.CharField(max_length=100, null=True, blank=True)
    slug = models.SlugField(unique=True)
    

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
import requests
from django.contrib.auth.models import Group
from django.contrib import messages
from django.utils.crypto import get_random_string

from .models import *

# group_required decorator


def group_required(*group_names):
    def in_group(u):
        return (u.is_superuser or bool(u.groups.filter(name__in=group_names)))
    return user_passes_test(in_group)


def group(request):
    groups = request.user.groups.all()
    return groups


# Create your views here.
@login_required
@group_required('Seller', 'Builder')
def dashboard(request):
    profile = Profile.objects.get(user=request.user)
    total_properties = Property.objects.filter(user_seller=profile).count()
    verified_properties = Property.objects.filter(
        user_seller=profile, is_verified=True).count()
    groups = group(request)

    total_projects = Project.objects.filter(builder=profile).count()
    verified_projects = Project.objects.filter(builder=profile,is_verified=True).count()
    context = {"groups": groups, "total_properties": total_properties,
               "verified_properties": verified_properties, "total_projects":total_projects, "verified_projects":verified_projects}
    return render(request, 'dashboardComponents/maindashboard.html', context)


def addproperty(request):
    states_url = "https://api.countrystatecity.in/v1/countries/IN/states"
    cities_url = "https://api.countrystatecity.in/v1/countries/IN/cities"
    headers = {
        'X-CSCAPI-KEY': 'blhwU1g0VUZ4Wm1lck8zeTg5WjZIN1dvZ0JHR09NUmJrcjlTYzVRZw=='
    }
    states = requests.request("GET", states_url, headers=headers).json()
    cities = requests.request("GET", cities_url, headers=headers).json()

    property_type = Property_type.objects.all()

    groups = group(request)
    context = {"states": states, "cities": cities,
               "groups": groups, "property_type": property_type}

    if request.method == "POST":
        property_purpose = request.POST.get('sr')
        property_type = request.POST.get('property_type')
        posting = request.POST.get('posting')
        address = request.POST.get('address')
        state = request.POST.get('state')
        city = request.POST.get('city')
        total_floors = request.POST.get('tf')
        floorno = request.POST.get('fn')
        area = request.POST.get('area')
        age_of_construction = request.POST.get('aoc')
        floors_allowed = request.POST.get('fafc')
        open_sides = request.POST.get('op')
        bountry_wall = request.POST.get('bw')
        furnished_status = request.POST.get('fs')
        monthly_rent = request.POST.get('mrent')
        maintenance_charges = request.POST.get('mc')
        price = request.POST.get('price')
        booking_price = request.POST.get('bprice')

        user = Profile.objects.get(user=request.user)
        property_no = get_random_string(8, "0123456789nirmal")
        property_obj = Property(
            user_seller=user,
            property_purpose=property_purpose,
            property_type=property_type,
            property_posting=posting,
            property_address = address,
            property_state=state,
            property_city=city,
            # property_total_floors=total_floors,
            # property_floor_no=floorno,
            # property_area=area,
            property_age_of_construction=age_of_construction,
            # property_floors_allowed_for_construction=floors_allowed,
            # property_no_of_open_sides=open_sides,
            property_bountry_wall=bountry_wall,
            property_furnished_status=furnished_status,
            # property_monthly_rent=monthly_rent,
            # property_maintenance_charges=maintenance_charges,
            # property_price=price,
            # property_booking_price=booking_price,
            dynamic_fields={"property_total_floors": total_floors,
                            "property_floor_no": floorno,
                            "property_area": area,
                            "property_floors_allowed_for_construction": floors_allowed,
                            "property_no_of_open_sides": open_sides,
                            "property_monthly_rent": monthly_rent,
                            "property_maintenance_charges": maintenance_charges,
                            "property_price": price,
                            "property_booking_price": booking_price
                            },
            property_no=property_no,
        )

        property_obj.save()

        property_image1 = request.FILES['image1']
        property_image2 = request.FILES['image2']
        property_image3 = request.FILES['image3']
        property_image4 = request.FILES['image4']
        property_image5 = request.FILES['image5']
        slug = get_random_string(8, "0123456789n")

        image_obj = Property_image.objects.create(property=property_obj,
                                                  image1=property_image1,
                                                  image2=property_image2,
                                                  image3=property_image3,
                                                  image4=property_image4,
                                                  image5=property_image5,
                                                  slug=slug
                                                  )
        image_obj.save()
        # list1 = [property_image1,property_image2,property_image3,property_image4,property_image5]

        # for i in list1:
        #     image_obj = Property_image.objects.create(property= property_obj, image1 = i)
        #     image_obj.save()
        messages.success(request, 'Property successfuly added.')

    return render(request, 'dashboardComponents/addproperty.html', context)


def addproject(request):
    states_url = "https://api.countrystatecity.in/v1/countries/IN/states"
    cities_url = "https://api.countrystatecity.in/v1/countries/IN/cities"
    headers = {
        'X-CSCAPI-KEY': 'blhwU1g0VUZ4Wm1lck8zeTg5WjZIN1dvZ0JHR09NUmJrcjlTYzVRZw=='
    }
    states = requests.request("GET", states_url, headers=headers).json()
    cities = requests.request("GET", cities_url, headers=headers).json()

    property_type = Property_type.objects.all()

    groups = group(request)
    context = {"states": states, "cities": cities,
               "groups": groups, "property_type": property_type}
    
    if request.method == "POST":
        projectname = request.POST.get('projectname')
        companyname = request.POST.get('companyname')
        property_type = request.POST.get('property_type')
        address = request.POST.get('address')
        state = request.POST.get('state')
        city = request.POST.get('city')
        total_floors = request.POST.get('tf')
        area = request.POST.get('area')
        furnished_status = request.POST.get('fs')
        price = request.POST.get('price')
        booking_price = request.POST.get('bprice')

        project_image1 = request.FILES['image1']
        project_image2 = request.FILES['image2']
        project_image3 = request.FILES['image3']
        project_image4 = request.FILES['image4']
        project_image5 = request.FILES['image5']
        booklet = request.FILES['booklet']
        slug = get_random_string(8, "0123456789n")
        user = Profile.objects.get(user=request.user)

        project_obj = Project(
            builder=user,
            projectname =projectname,
            companyname = companyname,
            property_type=property_type,
            property_address= address,
            property_state=state,
            property_city=city,
            property_furnished_status=furnished_status,
            dynamic_fields={"property_total_floors": total_floors,
                            "property_area": area,
                            "property_price": price,
                            "property_booking_price": booking_price
                            },
            booklet=booklet,
            image1=project_image1,
            image2=project_image2,
            image3=project_image3,
            image4=project_image4,
            image5=project_image5,
            slug=slug
        )
        project_obj.save()
        messages.success(request, 'Property successfuly added.')

    return render(request, 'dashboardComponents/addproject.html', context)


def allproperties(request):
    profile = Profile.objects.get(user=request.user)
    properties = Property.objects.filter(user_seller=profile)
    groups = group(request)
    if request.method == "POST":
        slug = request.POST.get('slug')
        property = Property.objects.get(user_seller=profile,property_no=slug)
        property.delete()
    context = {"groups": groups, "properties": properties}
    return render(request, 'dashboardComponents/allproperties.html', context)

def allprojects(request):
    profile = Profile.objects.get(user=request.user)
    projects = Project.objects.filter(builder=profile)
    groups = group(request)
    if request.method == "POST":
        slug = request.POST.get('slug')
        project = Project.objects.get(builder=profile,slug=slug)
        project.delete()
    context = {"groups": groups, "projects": projects}
    return render(request, 'dashboardComponents/allproject.html', context)


@login_required
def supervisordashboard(request):
    properties = Property.objects.all().count()
    propertyforverify = Property.objects.filter(is_verified=False).count()
    context = {"properties": properties, "verify": propertyforverify}
    return render(request, "dashboardComponents/supervisor/supervisordashboard.html", context)


@login_required
def property_verification(request):
    if request.method == "POST":
        slug = request.POST.get('slug')
        print(slug)

marketplace/templates/dashboardComponents/addproject.html
{% extends "dashboardComponents/dashboard.html" %}
{% load static %}

{% block title %}
Dashboard | builder
{% endblock title %}

{% block body %}

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <script>
        alert('{{ message }}');
    </script>
    {% endfor %}
</div>
{% endif %}

<!--Main Navigation-->
{% include "dashboardComponents/dashboardmenu.html" %}
<main>
    <div class="container-fluid">
        <div id="width" class="container-sm py-5 my-5 w-75">
            <form action="#" method="post" class="" enctype="multipart/form-data">

                <div id="pn" class="col-md-3">
                    <label for="" class="mb-2">Project name</label><br>
                    <input type="text" class="form-control" name="projectname" placeholder="Project name" />
                </div>
                <div id="cn" class="col-md-3">
                    <label for="" class="mb-2">Company name</label><br>
                    <input type="text" class="form-control" name="companyname" placeholder="Company name" />
                </div>
                <!-- property type -->
                <label for="" class="mb-2 fw-bold">Property type</label><br>
                <div class="input-group mb-4">
                    <select class="select form-control" name="property_type" id="property_type" required>
                        <option value="" disabled selected>Choose property type</option>
                        {% for i in property_type %}
                        <option value="{{i.property_type}}">{{i.property_type}}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Property location -->
                <label for="" class="mb-2 fw-bold">Property location</label><br><br>
                <div class="row">
                    <div class="col-md-12 input-group mb-4">
                        <input type="text" class="form-control" name="address" placeholder="address" />
                    </div>
                    <!-- states -->
                    <div class="col-md-6">
                        <div class="input-group mb-4">
                            <select class="select form-control" name="state" required>
                                <option value="" disabled selected>State</option>
                                {% for i in states%}
                                <option value="{{i.name}}">{{i.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <!-- cities -->
                    <div class="col-md-6">
                        <div class="input-group mb-4">
                            <select class="select form-control" name="city" required>
                                <option value="" disabled selected>City</option>
                                {% for i in cities %}
                                <option value="{{i.name}}">{{i.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div><br>

                <!-- property features -->
                <label for="" class="mb-4 fw-bold">Property Features</label><br>
                <div id="" class="row">

                    <!-- total floors -->
                    <div id="tf" class="col-md-3">
                        <label for="" class="mb-2">Total floors</label><br>
                        <input type="number" class="form-control" name="tf" placeholder="Total floors" />
                    </div>

                    <!-- area -->
                    <div class="col-md-3">
                        <label for="" class="mb-2">Area</label><br>
                        <input type="number" class="form-control" name="area" placeholder="...sq-ft" />
                    </div>
                </div>
                <div>
                </div><br>

                <!-- Furnished status -->
                <div id="fs">
                    <label for="" class="mb-2">Furnished Status</label><br>
                    <div class="btn-group mb-4">
                        <input type="radio" class="btn-check" name="fs" id="option5" value="Full Furnished" />
                        <label class="btn btn-secondary" for="option5">Full Furnished</label>

                        <input type="radio" class="btn-check" name="fs" id="option7" value="No Furnished" />
                        <label class="btn btn-secondary" for="option7">No Furnished</label>
                    </div>
                </div> <br>
                <div id="pd">
                    <label for="" class="mb-4 fw-bold">Price details</label><br>
                    <div class="row">
                        <!-- price -->
                        <div class="col-md-6">
                            <label for="" class="mb-2">Price</label><br>
                            <input type="text" name="price" class="form-control" placeholder="" />
                        </div>

                        <!-- Booking price -->
                        <div class="col-md-6">
                            <label for="" class="mb-2">Booking price</label><br>
                            <input type="number" name="bprice" class="form-control" placeholder="" />
                        </div>
                    </div>
                </div>
                <br>

                <!-- Images -->
                <label for="" class="mb-4 fw-bold">Photos</label><br>
                <input type="file" class="form-control" name="image1" placeholder="" required /><br>
                <input type="file" class="form-control" name="image2" placeholder="" required /><br>
                <input type="file" class="form-control" name="image3" placeholder="" required /><br>
                <input type="file" class="form-control" name="image4" placeholder="" required /><br>
                <input type="file" class="form-control" name="image5" placeholder="" required /><br>
                <!-- Submit button -->
                <label for="" class="my-4 fw-bold">Booklet</label>
                <input type="file" class="form-control" name="booklet" placeholder="" accept="application/pdf" required /><br>
                {% csrf_token %}

                <button type="submit" class="btn btn-primary mb-4">Submit</button>
                <p class="text-warning">Property verification is done within two working days.</p>
        </div>
    </div>
</main>

{% endblock body %}

marketplace/templates/dashboardComponents/allproject.html
{% extends "dashboardComponents/dashboard.html" %}
{% load static %}

{% block title %}
Dashboard | seller
{% endblock title %}

{% block body %}

{% include "dashboardComponents/dashboardmenu.html" %}
<main>
    <div class="container">
        <br>
        <br>
        <h2 class="my-4 ms-4">All Properties</h2>
        <table class="table">
            <thead class="bg-light">
                <tr>
                    <!-- <th scope="col">Sr.No.</th> -->
                    <th scope="col" class="fw-bold">Image</th>
                    <th scope="col" class="fw-bold">Property type</th>
                    <th scope="col" class="fw-bold">Address</th>
                    <th scope="col" class="fw-bold">city</th>
                    <th scope="col" class="fw-bold">state</th>
                    <th scope="col" class="fw-bold">status</th>
                    <th scope="col" class="fw-bold"></th>
                </tr>
            </thead>
            <tbody>
                {% for i in projects %}
                <tr>
                    <td><img src="{{ i.image1.url }}" alt="" style="width: 4rem;"></td>
                    <td>{{ i.property_type }}</td>
                    <td>{{ i.property_address }}</td>
                    <td>{{ i.property_city }}</td>
                    <td>{{ i.property_state }}</td>
                    {% if i.is_verified %}
                    <td><span class="badge badge-success rounded-pill d-inline">Verified</span></td>
                    {% else %}
                    <td><span class="badge badge-danger rounded-pill d-inline">Not verified</span></td>
                    {% endif %}

                    <td>
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="text" value="{{i.slug}}" name="slug" style="display: none;">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock body %}

marketplace/templates/dashboardComponents/dashboardmenu.html
{% load static %}
<!--Main Navigation-->
<header>
    <!-- Sidebar -->
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar bg-white ">
        <div class="position-sticky">
            <div class="list-group list-group-flush mx-2 mt-4">
                {% for i in groups %}
                {% if i.name == "Seller" %}
                <a href="{% url 'dashboard' %}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                    <span>{{ i.name }} Dashboard</span>
                </a>
                {% elif i.name == "Builder" %}
                <a href="{% url 'dashboard' %}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
                    <span>{{ i.name }} Dashboard</span>
                </a>
                {% endif %}
                
                <!-- <a href="#" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-chart-line fa-fw me-3"></i><span>Analytics</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action py-2 ripple">
                    <i class="fas fa-chart-bar fa-fw me-3"></i><span>Bookings</span>
                </a> -->
                {% if i.name == "Seller" %}
                <a href="{% url 'addproperty' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <span>Add Property</span>
                </a>
                
                <a href="{% url 'allproperties' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <span>All Properties</span>
                </a>

                {% elif i.name == "Builder" %}
                <a href="{% url 'addproject' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <span>Add Projects</span>
                </a>
                
                <a href="{% url 'allprojects' %}" class="list-group-item list-group-item-action py-2 ripple">
                    <span>All Projects</span>
                </a>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </nav>
    <!-- Sidebar -->
    <!-- Navbar -->
    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#sidebarMenu"
                aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Brand -->
            <span class="navbar-brand mb-0 h1 fw-bolder text-primary"><a href="{% url 'realestate:index' %}">Area360</a></span>
            <!-- Right links -->
            <ul class="navbar-nav d-flex flex-row">
                <!-- Avatar -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" href="#"
                        id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'img/avatar.png' %}" class="rounded-circle" height="22" alt="Avatar"
                            loading="lazy" />
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="{% url 'realestate:profile' %}">My profile</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Settings</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'realestate:logout' %}">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
</header>

marketplace/templates/dashboardComponents/propertylist.html
<div class="container p-3">
      <div class="container mt-5">
            <h2 class="h2-responsive text-center mb-0" id="home">Properties</h2>
      </div>
      <div class="row row-cols-1 row-cols-md-4 g-4 mt-3">
            {% if properties %}
            {% for i in properties %}
            {% if i.property.is_verified %}
            <a href="{% url 'realestate:property' slug=i.slug %}" class="text-normal text-body">
                  <div class="col">
                        <div class="card h-100">
                              <img src="/media/{{i.image1}}" class="card-img-top" alt="" style="height:12rem; object-fit: cover;"/>
                              <div class="card-body">
                                    <!-- <h5 class="card-title">Card title</h5> -->
                                    <span class="badge badge-primary">{{ i.property.property_purpose }}</span>
                                    <span class="badge badge-secondary">{{ i.property.property_type }}</span>
                                    <p class="card-text mt-2 fw-bold">
                                          ₹{{ i.property.dynamic_fields.property_monthly_rent }}{{ i.property.dynamic_fields.property_price }} | {{ i.property.dynamic_fields.property_area }} sq-ft.
                                    </p>
                                    <p class="m-0">{{ i.property.property_city }}, {{ i.property.property_state }}</p>
                              </div>
                        </div>
                  </div> 
            </a>
            {% endif %}
            {% endfor %}
            {% else %}
            <h2 class="h2-responsive my-4">No result found.</h2>
            {% endif %}
      </div>
</div>